create procedure sp_modificarEventoexp

@ID_EVENTO INT,
@FECHA DATE,
@TITULO VARCHAR(50),
@DESCRIPCION varchar(50),
@IDEXP INT
AS

UPDATE EVENTO 
 SET FECHA=@FECHA,TITULO=@TITULO,DESCRIPCION=@DESCRIPCION,ID_EXPEDIENTE=@IDEXP,ID_CONTACTO=0 WHERE @ID_EVENTO = EVENTO.ID_EVENTO

