create procedure sp_modificarEventoCont

@ID_EVENTO INT,
@FECHA DATE,
@TITULO VARCHAR(50),
@DESCRIPCION varchar(50),
@IDCONT INT
AS

UPDATE EVENTO 
 SET FECHA=@FECHA,TITULO=@TITULO,DESCRIPCION=@DESCRIPCION,ID_EXPEDIENTE=0,ID_CONTACTO=@IDCONT WHERE @ID_EVENTO = EVENTO.ID_EVENTO

